repos:
  # a set of useful Python-based pre-commit hooks
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        # list of definitions and supported hooks: https://pre-commit.com/hooks.html
        - id: trailing-whitespace      # removes any whitespace at the ends of lines
        - id: end-of-file-fixer        # makes sure files end in a newline and only a newline
        - id: check-yaml               # check yaml syntax by loading all yaml files
        - id: check-merge-conflict     # check for files with merge conflict strings
          args: ['--assume-in-merge']  #  and run this check even when not explicitly in a merge
        - id: check-added-large-files  # check that no "large" files have been added
          args: ['--maxkb=10240']      #  where large means 10MB+
        - id: debug-statements         # check for python debug statements (import pdb, breakpoint, etc.)
        - id: detect-private-key       # checks for private keys (BEGIN X PRIVATE KEY, etc.)

  # black python autoformatting
  -   repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
        - id: black
    # additional configuration of black in pyproject.toml

   # isort import sorting
  -   repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
        - id: isort
    # additional configuration of isort in pyproject.toml

  # pyupgrade python syntax upgrades
  -   repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
        - id: pyupgrade
          args: ['--py310-plus']
